### ISSUE TITLE
NFC emulator?

### ISSUE THREAD

**Issue by ertmuirm** [OLIET2357/HCEFUnlocker#2]
Does this allow Samsung phones to be able to do HCE emulation, e.g. via the NFC Card Emulator app?

**Comment by OLIET2357** [comment]
Also, it is impossible to add functions that are not originally in the hardware.

**Comment by OLIET2357** [comment]
This just unlocks the HCE-F restrictions.

**Comment by ertmuirm** [comment]
Thanks for the quick reply. What are the use cases for this mod, if I may ask?

**Comment by OLIET2357** [comment]
Thank you for your interest.
This aims to HCE-F, the HCE of "FeliCa" mainly used in Japan.
This unlocks the restrictions that HCE-F can not copy existing cards.
