### ISSUE TITLE
これの役割は何ですか？

### ISSUE THREAD

**Issue by Konne06** [OLIET2357/HCEFUnlocker#5]
これを使ったら、海外スマホもおサイフケータイアプリを使えますか？

**Comment by OLIET2357** [comment]
> これを使ったら、海外スマホもおサイフケータイアプリを使えますか？

いいえ。
専用のハードウェアが搭載されているおサイフケータイはソフトウェアではそう簡単に真似できません。

このモジュールの役割は、国内・海外スマホ問わず搭載されている FeliCa として振る舞う機能のうち、
既存のカードのパラメータを設定できない制限を解除することです。

紛らわしいですがおサイフケータイには暗号化されているハードウェアが搭載されているため、ソフトウェアで実装することは困難を極めるでしょう。
